### ISSUE TITLE
Use venv instead of virtualenv

### ISSUE THREAD

**Issue by mouradxmt** [xvik/gradle-use-python-plugin#77]
Is there a way to use venv instead of virtualenv? override the used tool.

**Comment by xvik** [comment]
No, only virtualenv supported. Initially it was required to support both pythons 2 and 3. Now its not as important, but it needs time to implement venv support. Maybe, someday I'll do it. 
Overall, it should not be a big problem as plugin would manage virtualenv installation and usage automatically. If there are problems with virtualenv please mention it (because I'm not aware of such problems and consider venv support as very low priority)

**Comment by mouradxmt** [comment]
Because starting with python 3.3, venv is included by default and does not require installing a package. and using the plugin with a new pre-installed python we won't have the requirement to install another module(virtualenv) since an alternative already exist.
Use case : Being a local user of the machine with no write access to the root python version... and this instance does not have virtualenv installed.. the plugin can't install virtualenv due to permission needed. it will be nice if the plugin can use venv instead.

**Comment by xvik** [comment]
Virtualenv should be installed for current user only (`--user`) and should not cause permission errors. But, it seems, it's not always work like that. I'll look to support venv, but later, when I have time (hopefullty this year)

**Comment by mouradxmt** [comment]
Thank you!

**Comment by xvik** [comment]
[4.0.0 released](https://github.com/xvik/gradle-use-python-plugin/releases/tag/4.0.0). Venv now used by default and falls back to virtualenv only if venv not found. There would be no problems with existing projects where environments were already created with virtualenv (venv/virtualenv used only for environment creation)
