### ISSUE TITLE
Missing configuration cache support

### ISSUE THREAD

**Issue by davireis** [xvik/gradle-use-python-plugin#89]
See error below:

```
 Plugin 'ru.vyarus.use-python': registration of listener on 'Gradle.buildFinished' is unsupported
 See https://docs.gradle.org/8.0.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners
```
  
  For more information on configuration cache: https://blog.gradle.org/introducing-configuration-caching

**Comment by xvik** [comment]
Yes, configuration cache is not supported yet because there was no alternative to buildFinished listener. But since 8.1 there is a [flowscope api](https://docs.gradle.org/8.1/release-notes.html#new-dataflow-actions-replace-buildfinished-listeners) which could be used instead.

I will try to use it and, in case of success, plugin would support build cache for gradle 8.1 and above and will fallback to old listener for older gradle versions. Can't promise it very soon, but not too long.

And, just for reference (to keep track), [configuration cache issue in mkdocs plugin](https://github.com/xvik/gradle-mkdocs-plugin/issues/23) (relative of this plugin).

**Comment by xvik** [comment]
[4.0.0 released](https://github.com/xvik/gradle-use-python-plugin/releases/tag/4.0.0) with configuration cache support
